# Generated by Django 2.0b1 on 2017-10-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnclaTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('tipo', models.CharField(max_length=100)),
                ('hora_inicio', models.IntegerField(blank=True, null=True)),
                ('hora_fin', models.IntegerField(blank=True, null=True)),
                ('dias', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id_centro', models.IntegerField(primary_key=True, serialize=False)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogar', to='app.AnclaTemporal')),
                ('jardin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jardin', to='app.AnclaTemporal')),
            ],
        ),
        migrations.CreateModel(
            name='IndividuoTiempoCentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('tiempo_caminando', models.IntegerField(blank=True, null=True)),
                ('tiempo_omnibus', models.IntegerField(blank=True, null=True)),
                ('tiempo_auto', models.IntegerField(blank=True, null=True)),
                ('cantidad_pediatras', models.IntegerField()),
                ('llega', models.CharField(max_length=2)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Centro')),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individuo')),
            ],
        ),
        migrations.CreateModel(
            name='MedidasDeResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadTotalLlega', models.IntegerField()),
                ('cantidadMaximaHoras', models.IntegerField()),
                ('cantidadHorasLunes', models.IntegerField()),
                ('cantidadHorasMartes', models.IntegerField()),
                ('cantidadHorasMiercoles', models.IntegerField()),
                ('cantidadHorasJueves', models.IntegerField()),
                ('cantidadHorasViernes', models.IntegerField()),
                ('cantidadHorasSabado', models.IntegerField()),
                ('cantidadTotalCentros', models.IntegerField()),
                ('cantidadCentrosLunes', models.IntegerField()),
                ('cantidadCentrosMartes', models.IntegerField()),
                ('cantidadCentrosMiercoles', models.IntegerField()),
                ('cantidadCentrosJueves', models.IntegerField()),
                ('cantidadCentrosViernes', models.IntegerField()),
                ('cantidadCentrosSabado', models.IntegerField()),
                ('centroOptimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Centro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individuo')),
            ],
        ),
        migrations.CreateModel(
            name='Pediatra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('cantidad_pediatras', models.IntegerField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Centro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_centroide', models.IntegerField()),
                ('y_centroide', models.IntegerField()),
                ('tipo_sector', models.CharField(max_length=20)),
                ('shape', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.FloatField()),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('sector_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_1', to='app.Sector')),
                ('sector_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_2', to='app.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='individuo',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prestador'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='tipo_transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoTransporte'),
        ),
        migrations.AddField(
            model_name='individuo',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajo', to='app.AnclaTemporal'),
        ),
        migrations.AddField(
            model_name='centro',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prestador'),
        ),
        migrations.AddField(
            model_name='centro',
            name='sector_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCentro_auto', to='app.Sector'),
        ),
        migrations.AddField(
            model_name='centro',
            name='sector_caminando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCentro_caminando', to='app.Sector'),
        ),
        migrations.AddField(
            model_name='anclatemporal',
            name='sector_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_auto', to='app.Sector'),
        ),
        migrations.AddField(
            model_name='anclatemporal',
            name='sector_caminando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_caminando', to='app.Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='sectortiempo',
            unique_together={('sector_1', 'sector_2')},
        ),
        migrations.AlterUniqueTogether(
            name='pediatra',
            unique_together={('centro', 'dia', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='individuotiempocentro',
            unique_together={('individuo', 'centro', 'dia', 'hora')},
        ),
    ]
