# Generated by Django 2.0 on 2018-02-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anclatemporal',
            name='sector_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_omnibus', to='app.SectorOmnibus'),
        ),
        migrations.AddField(
            model_name='centro',
            name='sector_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCentro_omnibus', to='app.SectorOmnibus'),
        ),
    ]
