# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasDeResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadTotalLlega', models.IntegerField()),
                ('cantidadMaximaHoras', models.IntegerField()),
                ('cantidadHorasLunes', models.IntegerField()),
                ('cantidadHorasMartes', models.IntegerField()),
                ('cantidadHorasMiercoles', models.IntegerField()),
                ('cantidadHorasJueves', models.IntegerField()),
                ('cantidadHorasViernes', models.IntegerField()),
                ('cantidadHorasSabado', models.IntegerField()),
                ('cantidadTotalCentros', models.IntegerField()),
                ('cantidadCentrosLunes', models.IntegerField()),
                ('cantidadCentrosMartes', models.IntegerField()),
                ('cantidadCentrosMiercoles', models.IntegerField()),
                ('cantidadCentrosJueves', models.IntegerField()),
                ('cantidadCentrosViernes', models.IntegerField()),
                ('cantidadCentrosSabado', models.IntegerField()),
                ('centroOptimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Centro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individuo')),
            ],
        ),
        migrations.RenameField(
            model_name='individuotiempocentro',
            old_name='tiempo_auto',
            new_name='tiempoViaje',
        ),
        migrations.RemoveField(
            model_name='individuotiempocentro',
            name='tiempo_caminando',
        ),
        migrations.RemoveField(
            model_name='individuotiempocentro',
            name='tiempo_omnibus',
        ),
    ]
