# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuotiempocentro',
            name='llega',
        ),
        migrations.AddField(
            model_name='individuo',
            name='parada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tCentroHogar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tCentroJardin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tHogarCentro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tHogarJardin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tHogarTrabajo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tJardinCentro',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tJardinTrabajo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tTrabajoHogar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individuotiempocentro',
            name='tTrabajoJardin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='individuotiempocentro',
            name='cantidad_pediatras',
            field=models.IntegerField(null=True),
        ),
    ]
