# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anclatemporal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='centro',
            table=None,
        ),
        migrations.AlterModelTable(
            name='individuo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pediatra',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prestador',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sector',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sectortiempo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='settings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipotransporte',
            table=None,
        ),
    ]
