# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorOmnibus',
            fields=[
                ('shapeid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('x_centroide', models.IntegerField()),
                ('y_centroide', models.IntegerField()),
                ('shapePosition', models.IntegerField()),
            ],
            options={
                'ordering': ['shapeid'],
            },
        ),
        migrations.AlterField(
            model_name='sectortiempoomnibus',
            name='sectorO_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorO_1', to='app.SectorOmnibus'),
        ),
        migrations.AlterField(
            model_name='sectortiempoomnibus',
            name='sectorO_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorO_2', to='app.SectorOmnibus'),
        ),
    ]
