# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
