# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171111_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuo',
            name='parada',
        ),
        migrations.AddField(
            model_name='anclatemporal',
            name='parada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
