# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171030_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centro',
            options={'ordering': ['id_centro']},
        ),
        migrations.AlterModelOptions(
            name='individuo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='individuotiempocentro',
            options={'ordering': ['individuo', 'centro', 'dia', 'hora']},
        ),
        migrations.AlterModelOptions(
            name='medidasderesumen',
            options={'ordering': ['persona']},
        ),
        migrations.AlterModelOptions(
            name='pediatra',
            options={'ordering': ['centro', 'dia', 'hora']},
        ),
        migrations.RenameField(
            model_name='medidasderesumen',
            old_name='cantidadTotalLlega',
            new_name='cantidadConsultasJueves',
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadConsultasLunes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadConsultasMartes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadConsultasMiercoles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadConsultasSabado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadConsultasViernes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadTotalConsultas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medidasderesumen',
            name='cantidadTotalHoras',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
