# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171014_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='id_shape',
            new_name='shape',
        ),
    ]
