# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_centro_parada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTiempoOmnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.FloatField()),
                ('sectorO_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorO_1', to='app.Sector')),
                ('sectorO_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorO_2', to='app.Sector')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sectortiempoomnibus',
            unique_together=set([('sectorO_1', 'sectorO_2')]),
        ),
    ]
