# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171016_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='tipo_sector',
            field=models.CharField(max_length=20),
        ),
    ]
