# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171016_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro',
            name='sector',
        ),
        migrations.AddField(
            model_name='centro',
            name='sector_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCentro_auto', to='app.Sector'),
        ),
        migrations.AddField(
            model_name='centro',
            name='sector_caminando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCentro_caminando', to='app.Sector'),
        ),
    ]
