# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171210_1239'),
        ('app', '0005_auto_20171227_1734'),
    ]

    operations = [
    ]
