# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171016_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectortiempo',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectortiempo',
            name='tiempo',
            field=models.FloatField(),
        ),
    ]
