# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_individuotiempocentro_llegageofrafico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individuotiempocentro',
            old_name='llegaGeofrafico',
            new_name='llegaGeografico',
        ),
    ]
