# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectortiempo',
            name='sector_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_1', to='app.Sector'),
        ),
        migrations.AlterField(
            model_name='sectortiempo',
            name='sector_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_2', to='app.Sector'),
        ),
    ]
