# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171022_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuotiempocentro',
            name='cantidad_pediatras',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
