# Generated by Django 2.0 on 2018-01-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171228_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='centro',
            name='parada',
        ),
    ]
