# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_individuotiempocentro_cantidad_pediatras'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuotiempocentro',
            name='llega',
            field=models.CharField(default='No', max_length=2),
            preserve_default=False,
        ),
    ]
