# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180113_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuotiempocentro',
            name='llega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
