# Generated by Django 2.0 on 2018-01-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_anclatemporal_parada'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividuoCentroOptimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tHogarCentroAuto', models.IntegerField(null=True)),
                ('tHogarCentroCaminando', models.IntegerField(null=True)),
                ('tHogarCentroOmnibus', models.IntegerField(null=True)),
                ('centroOptimoAuto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroOptimoAuto', to='app.Centro')),
                ('centroOptimoCaminando', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroOptimoCaminando', to='app.Centro')),
                ('centroOptimoOmnibus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroOptimoOmnibus', to='app.Centro')),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Individuo')),
            ],
        ),
    ]
