# Generated by Django 2.0 on 2018-02-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_individuocentrooptimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTiempoCaminando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.FloatField()),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('sector_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCaminando_1', to='app.Sector')),
                ('sector_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectorCaminando_2', to='app.Sector')),
            ],
        ),
        migrations.RenameModel(
            old_name='SectorTiempo',
            new_name='SectorTiempoAuto',
        ),
        migrations.AlterUniqueTogether(
            name='sectortiempocaminando',
            unique_together={('sector_1', 'sector_2')},
        ),
    ]
