# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180217_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorauto',
            old_name='shapeId',
            new_name='shapeid',
        ),
        migrations.RenameField(
            model_name='sectorcaminando',
            old_name='shapeId',
            new_name='shapeid',
        ),
    ]
